### ISSUE TITLE
NODU is sometimes 2 for cluster with only 1 generating unit

### ISSUE THREAD

**Issue by janusdebondt** [AntaresSimulatorTeam/Antares_Simulator#57] opened 2020-10-01 14:27 UTC
We are observing cases where the Antares output variable NODU is resulting in 2 (viewing per separate Monte Carlo year, on hourly basis), although there is only one unit defined in the thermal cluster. The NODU variable will change from 2 to 0 and back to 2. The output of the respective cluster is also not above its defined capacity.

**Comment by PPlessiez** [comment] 2021-03-30 07:16
Could you please attach to this ticket an example of an Antares study for which the problem is experienced? It will help us investigate the root cause of the issue.

**Comment by janusdebondt** [comment] 2021-03-30 07:30
Hi @PPlessiez ,

I was in the meantime able to identify non-integer capacities (which are rounded up) as the root cause of this issue. Please see attached study as example. The example features:
- One unit with capacity of 500.9 MW
- It is dispatched at 501 MW which is OK, but the NODU is put to 2 although there is only one unit

Although indeed the GUI doesn't allow to insert non-integer numbers, studies created e.g. by scripts can have this issue.

[NODU test.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/6227180/NODU.test.zip)

With kind regards,
Janus

**Comment by PPlessiez** [comment] 2021-04-01 07:24
Hi @janusdebondt,
Thanks a lot for your clear answer and the associated example! We'll discuss within the team whether it would be easy to solve this rounding issue in the NODU calculation.

<u>For dev team:</u>

When a cluster is created via a script, the attribute "nominalcapacity" of the corresponding cluster in thermal/clusters/area/list.ini can have decimals.
These decimals are not taken into account when calculating the production of a cluster in the output, which can result in a NODU > the number of units of the clusters if the nominal capacity is rounded up.

**Comment by flomnes** [comment] 2021-04-21 08:41
Fixed by #231

**Closed by flomnes** 2021-04-21 08:41 UTC
Labels: bug, feature
