### ISSUE TITLE
There are no simulation results in the output folder in case when area contains more than nine renewable clusters

### ISSUE THREAD

**Issue by matijaosmosian** [AntaresSimulatorTeam/Antares_Simulator#867] opened 2022-09-17 19:56 UTC
**Description**
There are no simulation results in the output folder in case when area contains more than nine renewable clusters.

**How to Reproduce**

1. Open new empty ANTARES study (v 8.1 or higher). Add a new area and create renewable cluster inside the area.
2. Run the simulation and open the results. There will be results of the simulation in the output.
3. Clone renewable cluster more than nine times (in order to have more than nine renewable clusters inside the area)
4. Run the simulation and go to the results. The output will be empty.
5. Check the output folder.

**Expected behavior**
The results of the simulation should be present in the output, inside economy folder. 

**Screenshots and additional files**
![image](https://user-images.githubusercontent.com/77788527/190873970-5eca7973-8285-478a-92d1-31bf6f3418aa.png)

![image](https://user-images.githubusercontent.com/77788527/190873989-a3a01703-55d8-4cea-8b6a-74d7e571ecdd.png)

**OS and version**
 - OS: Windows
 - Antares Simulator version: 8.2
[Renewable_clusters.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/9592514/Renewable_clusters.zip)

**Comment by flomnes** [comment] 2022-09-19 07:59
Thank you for reporting this bug. I suspect it was fixed by #753 (merged in v8.3.0), @payetvin will check.

**Comment by matijaosmosian** [comment] 2022-09-19 08:32
Thank you for your reply. I have checked versions 8.3.0 and 8.3.1 and I can reproduce the bug. (versions downloaded from: https://github.com/AntaresSimulatorTeam/Antares_Simulator/releases)

**Comment by flomnes** [comment] 2022-09-19 08:59
Segfault in `yearEndBuildPrepareDataForEachRenewableCluster`, `src/solver/variable/economy/renewableGeneration.h:297`.

`pValuesForTheCurrentYear` is a 3D array. 

- 1st index is the `numSpace`, ie the thread where the job is (0 here, sequential execution)
- The 2nd index is the cluster group (0..nbGroups-1)
- The 3rd index is the hour in the year (0..8759)

The problem is that instead of accessing a group, we try to access an areaWideIndex. There are 9 columns, hence the crash if an area has more than 9 renewable clusters (@matijaosmosian's observation).

```cpp
state.renewableClusterProductionForYear[i]
  += pValuesForTheCurrentYear[numSpace][state.renewableCluster->areaWideIndex].hour[i];
```

**Comment by flomnes** [comment] 2022-09-19 13:33
#869 fixes the issue and will be merged into the next release. A few useless lines of code were causing the crash. Thanks again @matijaosmosian for reporting the issue to us.

**Closed as completed by flomnes** 2022-09-19 13:33 UTC
Labels: bug

**Comment by flomnes** [comment] 2022-10-01 12:50
Hi @matijaosmosian, [Antares Simulator v8.3.2](https://github.com/AntaresSimulatorTeam/Antares_Simulator/releases/tag/v8.3.2) fixes this issue, and was released today. Thanks for using Antares Simulator and helping us improve it.
